version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
      IPSTACK_API_KEY: ${IPSTACK_API_KEY}
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  test:
    build: .
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
      IPSTACK_API_KEY: ${IPSTACK_API_KEY}
    volumes:
      - ./app:/app
    depends_on:
      app:
        condition: service_started
    command: ["python", "-m", "pytest"]

volumes:
  postgres_data: